version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/financialboost
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - '8000:8080'
    depends_on:
      - postgres

  postgres:
    image: 'postgres:15.2'
    environment:
      - POSTGRES_DB=financialboost
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5435:5432'
