name: "DEV DEPLOY"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente para deploy"
        required: true
        default: "dev"

jobs:
  terraform:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: ${{ inputs.environment }}
      aws-assume-role-arn: arn:aws:iam::238309559213:role/github-actions-sergioRicJr-pipeline
      aws-statefile-s3-bucket: sergioricjr-us-east-1-terraform-state-file
      aws-lock-dynamodb-table: sergioricjr-us-east-1-terraform-lock
      aws-region: us-east-1